# Generated by Django 3.2.10 on 2022-05-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('image_category', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('image_location', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='No image', upload_to='images/')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mygallery.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mygallery.location')),
            ],
            options={
                'ordering': ['img_name'],
            },
        ),
    ]
